alerting:
  discord:
    webhook-url: "https://discord.com/api/webhooks/1155765999375761418/ff0t-C8C0bVYWMgQRizWriWwx8QzXz4J9jRU540v_lKil2OGe0phnOq6p4mrd2-Ndqbk"

endpoints:

  - name: dhiway.com
    url: "https://dhiway.com"
    interval: 1m
    conditions:
      - "[STATUS] == 200"
    alerts:
      - type: discord
        description: "healthcheck failed for https://dhiway.com"
        send-on-resolved: true

  - name: api.studio.dhiway.com
    url: "https://api.studio.dhiway.com/"
    interval: 1m
    conditions:
      - "[STATUS] == 200"
    alerts:
      - type: discord
        description: "healthcheck failed https://api.studio.dhiway.com"
        send-on-resolved: true

  - name: download.studio.dhiway.com
    url: "https://download.studio.dhiway.com"
    interval: 1m
    conditions:
      - "[STATUS] == 200"
    alerts:
      - type: discord
        description: "healthcheck failed https://download.studio.dhiway.com"
        send-on-resolved: true

  - name: verify.studio.dhiway.com
    url: "https://verify.studio.dhiway.com"
    interval: 1m
    conditions:
      - "[STATUS] == 200"
    alerts:
      - type: discord
        description: "healthcheck failed https://verify.studio.dhiway.com"
        send-on-resolved: true

  - name: seqr.dhiway.com
    url: "https://seqr.dhiway.com/api/v1/monitoring/ping"
    interval: 1m
    conditions:
      - "[STATUS] == 200"
    alerts:
      - type: discord
        description: "healthcheck failed https://seqr.dhiway.com"
        send-on-resolved: true

  - name: hashcode.studio.dhiway.com
    url: "https://hashcode.studio.dhiway.com/monitor"
    interval: 1m
    conditions:
      - "[STATUS] == 200"
    alerts:
      - type: discord
        description: "healthcheck failed https://hashcode.studio.dhiway.com"
        send-on-resolved: true
